### ISSUE TITLE
welcome jumbotron text

### ISSUE THREAD

**Issue by jelizarovas** [jelizarovas/HairByMargo.Com#11]
![image](https://user-images.githubusercontent.com/15138718/73409831-40afd380-42b5-11ea-9225-094777546c7f.png)

Current welcome screen on desktop computers. We need to change the text to quick about me description, maybe add image.

**Comment by salonmargo** [comment]
Marguerite Swan is an up and coming young entrepreneur and community activist who built her own custom salon through hard work and word of mouth recommendations. In addition to hair, she has renovated two salon spaces. Swan is a former foster child who passionately advocates for better resources and care for foster and adoptive youth. She also pushes for recognition and support for the first responders in her community. also born 11/11 Marguerite brings a joyful spark to everything she does rarely without a smile and laugh that naturally draws people in. ( you can reword it and make it fluent or even add to it. I asked clients to let me know what they thought of me)

**Comment by salonmargo** [comment]
About me: graduate of Paul Mitchell the school Danbury, Licenced since 2011 but worked with kids since a young age and built a children’s salon with my foster parents (Not sure if that should be left out but I’ve been working with kids for so many years) keratin educator and certified in extensions. I will figure out more to add about me. I’m a tad loopy

**Comment by salonmargo** [comment]
If you google Marguerite Swan Sundae Spa, you will find pictures from new haven registry of me in a blue shirt  putting a glitter tattoo on a girl and the original Sunday spa photo of me and my foster sister
